#pragma once

#define GME_APP_MAJOR     1
#define GME_APP_MINOR     8
#define GME_APP_REVIS     1
#define GME_APP_PATCH     3

#define STRINDIRECT(x) #x
#define STRVERSION(x) STRINDIRECT(x)
#define APPVERSIONSTR STRVERSION(GME_APP_MAJOR) "." STRVERSION(GME_APP_MINOR) "." STRVERSION(GME_APP_REVIS) "." STRVERSION(GME_APP_PATCH)